#!/usr/bin/env python3
"""
VibeCode OS — CLAUDE.md bridge (007+)
Generates and syncs a compact CLAUDE.md from AGENTS.md + PROJECT_CONTEXT.md.
CLAUDE.md is the Claude Code native memory surface loaded every session.
Python 3.8+, stdlib only.
"""

import os
import re

from context import atomic_write, _extract_section


# Sections in AGENTS.md that are workflow-critical.
# A conflict in these sections requires user resolution.
CRITICAL_SECTIONS = [
    "## Working Rules",
    "## Never Do",
    "## Project-specific rules",
]


def generate_claude_md(agents_path: str, project_context_path: str) -> str:
    """
    Generate a compact CLAUDE.md content string from AGENTS.md and
    PROJECT_CONTEXT.md. Returns the generated string.
    """
    lines = []
    lines.append("<!-- vibecode:claude-bridge:auto-generated -->")
    lines.append("<!-- Do not edit manually — regenerated by VibeCode OS on /vibe-start -->")
    lines.append("")

    # Project identity
    project_name = _extract_project_name(project_context_path)
    if project_name:
        lines.append(f"# {project_name} — Claude Context")
    else:
        lines.append("# Project Context")
    lines.append("")

    # Mission from AGENTS.md
    mission = _read_section(agents_path, "## Mission")
    if mission.strip():
        lines.append("## Mission")
        lines.append(mission.strip())
        lines.append("")

    # Working rules
    working_rules = _read_section(agents_path, "## Working Rules")
    if working_rules.strip():
        lines.append("## Working Rules")
        lines.append(working_rules.strip())
        lines.append("")

    # Never Do
    never_do = _read_section(agents_path, "## Never Do")
    if never_do.strip():
        lines.append("## Never Do")
        lines.append(never_do.strip())
        lines.append("")

    # Project-specific rules
    project_rules = _read_section(agents_path, "## Project-specific rules")
    if project_rules.strip() and "[TODO:" not in project_rules:
        lines.append("## Project-specific rules")
        lines.append(project_rules.strip())
        lines.append("")

    # Workflow commands
    lines.append("## VibeCode OS Commands")
    lines.append("- `/vibe-start` — spec and begin a new feature")
    lines.append("- `/vibe-resume` — restore session context (run at session start)")
    lines.append("- `/vibe-status` — check active feature progress")
    lines.append("- `/vibe-done` — verify and close the active feature")
    lines.append("")

    # Command registry from AGENTS.md
    registry = _extract_command_registry(agents_path)
    if registry:
        lines.append("## Verification Commands")
        for key, val in registry.items():
            lines.append(f"- `{key}`: `{val}`")
        lines.append("")

    return "\n".join(lines)


def sync_claude_md(root: str) -> dict:
    """
    Sync CLAUDE.md in root from AGENTS.md + PROJECT_CONTEXT.md.

    Returns a dict:
      - status: 'created' | 'updated' | 'unchanged' | 'conflict'
      - message: human-readable description
      - conflicts: list of conflicting section names (empty unless status='conflict')
    """
    agents_path = os.path.join(root, "AGENTS.md")
    project_path = os.path.join(root, "PROJECT_CONTEXT.md")
    claude_path = os.path.join(root, "CLAUDE.md")

    generated = generate_claude_md(agents_path, project_path)

    if not os.path.exists(claude_path):
        atomic_write(claude_path, generated)
        return {"status": "created", "message": "CLAUDE.md created", "conflicts": []}

    existing = _read_file_safe(claude_path)

    # Check if existing was auto-generated by us (safe to overwrite)
    if "<!-- vibecode:claude-bridge:auto-generated -->" in existing:
        if existing.strip() == generated.strip():
            return {"status": "unchanged", "message": "CLAUDE.md already up to date", "conflicts": []}
        atomic_write(claude_path, generated)
        return {"status": "updated", "message": "CLAUDE.md updated", "conflicts": []}

    # Existing file was manually edited — check for critical section conflicts
    conflicts = _find_critical_conflicts(existing, generated)
    if conflicts:
        return {
            "status": "conflict",
            "message": (
                f"CLAUDE.md has manual edits that conflict with AGENTS.md in: "
                f"{', '.join(conflicts)}. Resolve before continuing."
            ),
            "conflicts": conflicts,
        }

    # Non-critical divergence — warn but proceed with update, preserving manual header
    atomic_write(claude_path, generated)
    return {
        "status": "updated",
        "message": "CLAUDE.md updated (non-critical manual edits overwritten)",
        "conflicts": [],
    }


def _find_critical_conflicts(existing: str, generated: str) -> list:
    """
    Check if critical sections differ between existing and generated content.
    Returns list of section names that conflict.
    """
    conflicts = []
    for section in CRITICAL_SECTIONS:
        existing_sec = _extract_section(existing, section).strip()
        generated_sec = _extract_section(generated, section).strip()
        if existing_sec and generated_sec and existing_sec != generated_sec:
            # Only flag as conflict if existing has non-template content
            if "[TODO:" not in existing_sec:
                conflicts.append(section)
    return conflicts


def _extract_project_name(project_context_path: str) -> str:
    """Extract project name from PROJECT_CONTEXT.md."""
    content = _read_file_safe(project_context_path)
    # Look for "- Name: ..." pattern
    m = re.search(r"-\s*Name:\s*(.+)", content)
    if m:
        return m.group(1).strip()
    # Fall back to first H1
    m = re.search(r"^#\s+(.+)", content, re.MULTILINE)
    if m:
        return m.group(1).strip()
    return ""


def _read_section(path: str, heading: str) -> str:
    content = _read_file_safe(path)
    return _extract_section(content, heading)


def _extract_command_registry(agents_path: str) -> dict:
    """Extract declared command registry entries from AGENTS.md."""
    content = _read_file_safe(agents_path)
    registry = {}
    keys = ["verify_cmd", "test_cmd", "lint_cmd", "typecheck_cmd", "build_cmd"]
    for key in keys:
        pattern = rf"{key}:\s*(.+)"
        m = re.search(pattern, content)
        if m:
            val = m.group(1).strip()
            if val and "[TODO:" not in val:
                registry[key] = val
    return registry


def _read_file_safe(path: str) -> str:
    if not path or not os.path.exists(path):
        return ""
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            return f.read()
    except OSError:
        return ""
